CREATE OR REPLACE TABLE `birkbeck-msc-project-422917.extract_layer.all_api_sportdevs_fb_teams`

(
`coach_name` STRING,
    `coach_id` INT64,
    `arena_hash_image` STRING,
    `arena_name` STRING,
    `arena_id` INT64,
    `primary_league_hash_image` STRING,
    `primary_league_id` INT64,
    `color_secondary` STRING,
    `tournament_id` INT64,
    `coach_hash_image` STRING,
    `national` BOOLEAN,
    `class_hash_image` STRING,
    `class_name` STRING,
    `tournament_name` STRING,
    `class_id` INT64,
    `country_name` STRING,
    `country_hash_image` STRING,
    `country_id` INT64,
    `foundation_date` TIMESTAMP,
    `color_text` STRING,
    `type` INT64,
    `color_primary` STRING,
    `name_code` STRING,
    `id` INT64,
    `gender` STRING,
    `short_name` STRING,
    `primary_league_name` STRING,
    `full_name` STRING,
    `name` STRING,
    `hash_image` STRING
)
