CREATE OR REPLACE TABLE `birkbeck-msc-project-422917.extract_layer.api_sportdevs_fb_matches`

(
`time` STRING,
    `end_time` TIMESTAMP,
    `graphs_id` INT64,
    `league_hash_image` STRING,
    `league_name` STRING,
    `league_id` INT64,
    `coaches_id` INT64,
    `lineups_id` INT64,
    `class_id` INT64,
    `duration` INT64,
    `start_time` TIMESTAMP,
    `class_name` STRING,
    `specific_start_time` TIMESTAMP,
    `id` INT64,
    `times` RECORD,
    `attendance` INT64,
    `home_team_score` RECORD,
    `tournament_importance` INT64,
    `home_team_name` STRING,
    `home_team_id` INT64,
    `away_team_name` STRING,
    `arena_hash_image` STRING,
    `class_hash_image` STRING,
    `home_team_hash_image` STRING,
    `arena_name` STRING,
    `arena_id` INT64,
    `referee_id` INT64,
    `status_type` STRING,
    `referee_name` STRING,
    `status` RECORD,
    `tournament_name` STRING,
    `last_period` STRING,
    `previous_leg_match_id` INT64,
    `referee_hash_image` STRING,
    `round_id` INT64,
    `season_id` INT64,
    `round` RECORD,
    `tournament_id` INT64,
    `name` STRING,
    `coaches` RECORD,
    `away_team_score` RECORD,
    `away_team_id` INT64,
    `season_name` STRING,
    `away_team_hash_image` STRING
)
